### ISSUE TITLE
vue cli 项目解析路径失败

### ISSUE THREAD

**Issue by lyl123321** [SilurianYang/uni-read-pages#1]
const rootPath={
	true:'',
	false:path.resolve(process.cwd(), 'node_modules')
}
resolvePath(dir){
	return path.resolve(rootPath[this.CONFIG.cli],dir);
}

vue-cli 项目运行的是 path.resolve(‘’，dir)，解析为 root+dir,
应该用 path.resolve('node_modules',  dir）或者直接用 dir.

**Comment by SilurianYang** [comment]
设置 `cli:true ` 不就可以了？

**Comment by lyl123321** [comment]
> 设置 `cli:true ` 不就可以了？

设置 `cli:true` 时，path.resolve(‘’，'webpack') 的结果是  工作目录 + webpack ，中间少了个 node_modules

**Comment by SilurianYang** [comment]
发版时亲测可以的！你确定没弄错？

**Comment by lyl123321** [comment]
我是用 `vue-cli` 命令行创建的 `uni-app` 项目，
我的项目 `vue.config.js` 如下：
```
const TransformPages = require('uni-read-pages');
const tfPages = new TransformPages({
  cli: true,
  includes: ['path', 'name']
  // includes:['path', 'aliasPath', 'name', 'meta']
});

module.exports = {
  transpileDependencies: [
    'uni-simple-router'
  ],
  configureWebpack: {
    plugins: [
      new tfPages.webpack.DefinePlugin({
        ROUTES: JSON.stringify(tfPages.routes)
      })
    ]
  }
}
```
我的项目路径： 
/e/HBuilderProjects/mall-app

报错：
Cannot find module `'E:\HBuilderProjects\mall-app\webpack'`             
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)      
at Function.Module._resolveFilename (E:\HBuilderProjects\mall-app\node_modul es\module-alias\index.js:49:29)                                                      
at Function.Module._load (internal/modules/cjs/loader.js:562:25)                 
at Module.require (internal/modules/cjs/loader.js:692:17)                        
at require (internal/modules/cjs/helpers.js:25:18)                               
at new TransformPages (E:\HBuilderProjects\mall-app\node_modules\uni-read-pa ges\index.js:14:16)                                                                  at Object. (E:\HBuilderProjects\mall-app\vue.config.js:3:17)
--

设置 `cli: false`  时可正常运行

**Comment by SilurianYang** [comment]
对不起  打扰了
